# Generated by Django 5.2 on 2025-04-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_product',
            field=models.BooleanField(default=False),
        ),
    ]
